package com.tinyhouse.enums;
public enum NotificationType { RESERVATION_CREATED, RESERVATION_CONFIRMED, RESERVATION_CANCELLED, RESERVATION_REJECTED, PAYMENT_COMPLETED, PAYMENT_FAILED, REVIEW_RECEIVED, SYSTEM_ANNOUNCEMENT }
